web/models/analysis.py, web/models/run.py, web/resources/analysis.py, web/tests/api/test_analyses.py, web/tests/test_models.py
=> Api bug fixes

web/frontend/package.json, web/frontend/src/AnalysisList.tsx, web/frontend/src/App.test.tsx, web/frontend/src/App.tsx, web/frontend/src/Browse.tsx, web/frontend/src/Builder.tsx, web/frontend/src/HelperComponents.tsx, web/frontend/src/Home.tsx, web/frontend/src/MainSuite.test.tsx, web/frontend/src/Options.tsx, web/frontend/src/Overview.tsx, web/frontend/src/Predictors.tsx, web/frontend/src/Status.tsx, web/frontend/src/Transformations.tsx, web/frontend/src/commontypes.ts, web/frontend/src/coretypes.ts, web/frontend/src/setupTests.ts, web/frontend/src/transforms.ts, web/frontend/src/utils.ts, web/frontend/src/utils.tsx, web/frontend/tslint.json, web/frontend/yarn.lock
Major UI updates including:
- New transformation tab with the ability to add, delete and reorder transformations
- New options tab
- Browse public analyses 
- Various bug fixes and UI updates
- Preliminary suite of frontend tests
=> Tansformations, options, browse public analyses, etc

web/models/analysis.py, web/resources/analysis.py
=> Added contrast field to analyses

docker-compose.yml, web/config/forrest_movie.yml, web/config/movie.json, web/manage.py, web/populate.py, web/requirements.txt, web/scripts/nuke_docker_db.sh, web/tests/conftest.py
- Better ingestion function docstrings
- Added options necessary for long event files (skip_predictors)
- Added movie and stim_file to studyforrest in fork.
- Ingested fork
=> Modified ingestion functions (and dataset) to ingest studyforrest 

web/frontend/DEVNOTES.md, web/frontend/src/AnalysisList.tsx, web/frontend/src/App.tsx, web/frontend/src/Browse.tsx, web/frontend/src/Builder.tsx, web/frontend/src/Contrasts.tsx, web/frontend/src/HelperComponents.tsx, web/frontend/src/Home.tsx, web/frontend/src/MainSuite.test.tsx, web/frontend/src/Options.tsx, web/frontend/src/Overview.tsx, web/frontend/src/Predictors.tsx, web/frontend/src/Status.tsx, web/frontend/src/Transformations.tsx, web/frontend/src/coretypes.ts, web/frontend/src/index.tsx, web/frontend/src/setupTests.ts, web/frontend/src/transforms.ts, web/frontend/src/utils.ts
This PR doesn't include any logic changes. See #121
=> Formatting updates

web/frontend/src/AnalysisList.tsx, web/frontend/src/App.tsx, web/frontend/src/Browse.tsx, web/frontend/src/Builder.tsx, web/frontend/src/Home.tsx
Several UI enhancements including:
- Tabular view of analyses on the homepage
- Redirect user to homepage on logout
- Ask for confirmation before logging out
=> UI updates

README.md, neuroscout/db_utils.py, neuroscout/manage.py, neuroscout/models/analysis.py, neuroscout/models/predictor.py, neuroscout/models/run.py, neuroscout/models/stimulus.py, neuroscout/models/task.py, neuroscout/populate.py, neuroscout/resources/analysis.py, neuroscout/tests/api/test_analyses.py, neuroscout/tests/api/test_dataset.py, neuroscout/tests/api/test_predictor.py, neuroscout/tests/api/test_run_task.py, neuroscout/tests/conftest.py, neuroscout/tests/test_models.py
=> Misc bug fixes/enhancements

neuroscout/resources/analysis/endpoints.py, neuroscout/resources/analysis/schemas.py, neuroscout/tests/api/test_analyses.py, neuroscout/tests/conftest.py
- Add preproc and dataset addresses
=> Add bundle fields / transformation tests

.gitignore, README.md, docker-compose.yml
- README is up to date to recent updates
- Can export `DATASET_DIR` variable to configure `/datasets` remote volume.
=> Enable flexible volumes in docker-compose.yml and updated REAME

.travis.yml, neuroscout/config/example_config.py
Fix travis w/ new config file (example_config)
=> Moved config file in Travis testing

.travis.yml, neuroscout/Dockerfile, neuroscout/config/example_app.py, neuroscout/config/image_current.json, neuroscout/manage.py, neuroscout/models/features.py, neuroscout/models/predictor.py, neuroscout/populate/extract.py, neuroscout/populate/ingest.py, neuroscout/requirements.txt, neuroscout/resources/predictor.py, neuroscout/tests/api/test_predictor.py, neuroscout/tests/conftest.py, neuroscout/tests/test_models.py, neuroscout/update.txt
Addresses #168 and #162 
To-do
=> Versioning

celery_worker/requirements.txt, celery_worker/tasks.py, neuroscout/models/predictor.py, neuroscout/models/run.py, neuroscout/populate/extract.py
Link from PEs back to original stimulus
=> Keep track of stim in PEs

celery_worker/requirements.txt, celery_worker/tasks.py, neuroscout/config/feature_schema.json, neuroscout/config/merlin.json, neuroscout/models/analysis.py, neuroscout/populate/convert.py, neuroscout/populate/ingest.py, neuroscout/populate/utils.py, neuroscout/requirements.txt, neuroscout/resources/utils.py, postgres/pg_dump-to-s3/pg_dump-to-s3.sh
Minor fixes to ingest, convert and extract from Merlin Dataset, and pybids updates
Also addresses: #211
=> Ingest Merlin Dataset

neuroscout/frontend/package.json, neuroscout/frontend/src/App.tsx, neuroscout/frontend/src/Builder.tsx, neuroscout/resources/user.py, neuroscout/templates/confirm.html
Change made when launching at alpha website
=> Public changes

neuroscout/config/transformers.json, neuroscout/populate/convert.py, neuroscout/populate/extract.py, neuroscout/populate/ingest.py
Various minor fixes to extraction logic
=> Fixed to extract auditory features

celery_worker/tasks.py
Minor patch to allow compilation to work with new pybids
=> pybids dataset description patch

celery_worker/tasks.py, neuroscout/populate/transform.py
Various small fixes to get models running
=> Resample rate, and duration in shot change

celery_worker/tasks.py, neuroscout/config/feature_schema.json, neuroscout/config/transformers.json, neuroscout/requirements.txt
=> Handle N/As

neuroscout/models/dataset.py, neuroscout/resources/dataset.py, neuroscout/tests/api/test_dataset.py
=> Performance improvements to API

celery_worker/tasks.py, neuroscout/config/raiders.json, neuroscout/populate/extract.py, neuroscout/populate/modify.py, neuroscout/resources/run.py
Propagates derived stims and extracted features to new runs (added after initial ingest/extraction).
Closes #208 
WIP. Needs tests.
=> Allow partial propagation of derived stims and extracted features

.gitignore, celery_worker/tasks.py, docker-compose.yml, nginx/Dockerfile, nginx/sites-enabled/flask_project
- Updates cipher list using Cipherli.st recommendations, as well as other SSL related settings
- Fixes gitignore file to hide frontend config file
- Updates use of pybids in celery
=> Updates to NGINX security, and minor pybids update

celery_worker/requirements.txt, neuroscout/frontend/src/config.ts, neuroscout/requirements.txt
Ensure apispec and pybids versions are set correctly, and tests pass.
Closes #276
=> Update requirements- pybids/apisec

neuroscout/frontend/src/App.tsx, neuroscout/frontend/src/Builder.tsx, neuroscout/frontend/src/Home.tsx, neuroscout/frontend/src/Overview.tsx, neuroscout/frontend/src/Predictors.tsx, neuroscout/frontend/src/coretypes.ts
Fixes bug when filtering and selecting a new predictor all the unseen but selected predictors would be dropped.
Fixes issues with removing predictors from side bar not being properly removed from table.
Fixes removing predictor from main list not also being removed from selected hrf predictors.
=> Fixes bugs in prediction selection.

neuroscout/frontend/src/Builder.tsx, neuroscout/frontend/src/Contrasts.tsx, neuroscout/frontend/src/MainSuite.test.tsx, neuroscout/frontend/src/Options.tsx, neuroscout/frontend/src/Overview.tsx, neuroscout/frontend/src/Predictors.tsx, neuroscout/frontend/src/Transformations.tsx, neuroscout/frontend/src/coretypes.ts
=> make description/predictions editable and delay loading predictors

neuroscout/requirements.txt
Github alterted a Flask vulnerability. Updating Flask.
=> Fix vulnerability

neuroscout/frontend/src/Builder.tsx, neuroscout/frontend/src/coretypes.ts
=> update typing for runs and predictors

neuroscout/frontend/src/Builder.tsx, neuroscout/frontend/src/coretypes.ts, nginx/sites-enabled/ssl_config
fixes #356.
Has fixes from #357 in initial push might merge that one first.
=> https redirect

neuroscout/frontend/src/App.tsx, neuroscout/frontend/src/Builder.tsx, neuroscout/frontend/src/ContrastEditor.tsx
Left in the messages related to registration and errors from form validation.
=> remove debug messages

neuroscout/frontend/src/Builder.tsx, neuroscout/frontend/src/Contrasts.tsx, neuroscout/frontend/src/Options.tsx
fixes #324 
Also fixes bug where autocontrasts wasn't properly loading from loadAnalysis function.
=> move autocontrast to contrast tab

neuroscout/populate/annotate.py, neuroscout/populate/ingest.py
=> Ingest confounds as fmriprep

neuroscout/frontend/package.json, neuroscout/frontend/src/Builder.tsx, neuroscout/frontend/src/Predictors.tsx, neuroscout/frontend/src/coretypes.ts, neuroscout/frontend/src/utils.ts
=> Move HRF selection to its own tab.

neuroscout/frontend/src/App.css, neuroscout/frontend/src/Builder.tsx, neuroscout/frontend/src/ContrastEditor.tsx, neuroscout/frontend/src/Contrasts.tsx, neuroscout/frontend/src/Report.tsx, neuroscout/frontend/src/Review.tsx, neuroscout/frontend/src/Transformations.tsx, neuroscout/frontend/src/coretypes.ts, neuroscout/frontend/src/transforms.ts
So far, I've gone through and CamelCase'd a bunch of stuff, and changed some names (e.g. `Steps`).
TBH, I haven't put much thought into this aside from go off the compiler's errors, but so far it seems to be working ok. 
Please take a look @rwblair
=> Update BIDS StatsModel produced by frontend

celery_worker/tasks.py, neuroscout/frontend/src/Status.tsx, neuroscout/populate/ingest.py, neuroscout/populate/utils.py, neuroscout/tests/test_models.py
Fix #396 and #411 
Also updated live database
=> BIDS Derivatives RC1 compliance

neuroscout/resources/analysis/endpoints.py, neuroscout/tests/api/test_analyses.py
=> Only allow cloning of PASSED analyses

neuroscout/config/datasets/forrest.json, neuroscout/config/datasets/god.json, neuroscout/config/datasets/hbn.json, neuroscout/config/datasets/life.json, neuroscout/config/datasets/merlin.json, neuroscout/config/datasets/raiders.json, neuroscout/config/predictor_schema.json, neuroscout/populate/ingest.py, neuroscout/tests/test_models.py
Minor improvements + flaking of ingestion functions
Helps close #431
=> Misc improvements to ingestion

README.md
=> Update README to detail how to build frontend

.env.example, .pliersenv.example, README.md, neuroscout/config/example_app.py, neuroscout/core.py, neuroscout/manage.py, neuroscout/models/predictor.py, neuroscout/populate/ingest.py, neuroscout/requirements.txt
The documentation was out of date, so I've updated it here to make it a bit more comprehensive. 
@Shotgunosine take a look please and let me know what else I can do to make it easier to set up. 
Edit: Also addressing a few ingestion issues that came up, including:
- Grabbit/pybids deps
- Skip stimuli ingestion if there are none
- Update manage.py/add_task parameters
- Fix regex for finding non numeric values (for automatic computations)
=> Update README documentation

neuroscout/config/datasets/forrest.json, neuroscout/manage.py, neuroscout/populate/convert.py, neuroscout/populate/extract.py, neuroscout/populate/ingest.py, neuroscout/populate/json.py
Added some print statements to make it easier to know the status.
=> Minor extraction fixes

neuroscout/models/stimulus.py, neuroscout/tests/test_models.py
Minor fix which allowed me to expand the predictors to new HBN runs.
=> Add lazy dynamic to stimuli prop

neuroscout/frontend/src/AnalysisList.tsx, neuroscout/frontend/src/App.tsx, neuroscout/frontend/src/Builder.tsx, neuroscout/frontend/src/Contrasts.tsx, neuroscout/frontend/src/Predictors.tsx, neuroscout/frontend/src/Status.tsx, neuroscout/frontend/src/Transformations.tsx, neuroscout/resources/analysis/endpoints.py
Includes fixes for #421 #468 and #408
=> Random bug grab bag.

celery_worker/tasks.py
Closes #496 
Issue was that nistats cannot handle any n/as, so added fitlins code to impute first TR for confounds
=> Fix design matrix plots with n/as

neuroscout/frontend/src/Builder.tsx
=> Unbreak status tab maybe

neuroscout/resources/analysis/endpoints.py
Minor fix: clear runs before delete
=> Minor fix: Clear runs before delete

celery_worker/requirements.txt, neuroscout/populate/ingest.py, neuroscout/requirements.txt
Update to pybids 0.8, once released.
=> pybids 0.8 updates

neuroscout/resources/analysis/endpoints.py
=> Add exception for name PUT when locked

celery_worker/tasks.py, neuroscout/requirements.txt, neuroscout/resources/analysis/reports.py
=> Add additional (required) neurovault meta-data

neuroscout/Dockerfile, neuroscout/requirements.txt
- Fixes SQLAlchemy and Jinja vulnerabilities
- Simplifies Docker file for faster building
- Fixes issue with installing Node
=> Fix github vulnerabilities

neuroscout/resources/analysis/endpoints.py, neuroscout/resources/utils.py, neuroscout/tests/api/test_analyses.py
- Basic upgrade to analysis API route
=> Add kwarg options to GET analysis

docker-compose.yml, neuroscout/config/example_app.py
=> Add postgres password to docker-compose and example config

neuroscout/config/datasets/ds001338.json, neuroscout/config/datasets/ds001545.json, neuroscout/config/datasets/forrest.json, neuroscout/config/datasets/hbn.json, neuroscout/config/datasets/life.json, neuroscout/config/datasets/raiders.json, neuroscout/config/feature_schema.json
Updates transformations.json and dataset configs.
=> Extract additional language features

celery_worker/tasks.py, celery_worker/viz.py, docker-compose.yml, neuroscout/config/bibliography.json, neuroscout/resources/analysis/endpoints.py, neuroscout/resources/analysis/reports.py
- Fixes #560 and adds bilbiography entries for more `PredefinedDictionaries` (massiveauditorylexicaldecision, calgarysemanticdecision, and concreteness)
- Fixes #567 
- Fixes AWS access for sql backup script.
=> Fix bibliography + database backups, add scaling to DM plots

neuroscout/frontend/src/App.tsx
Remove unfinished feature appendages
=> Remove links to unfinished features

celery_worker/tasks.py, neuroscout/resources/analysis/reports.py
- Only upload t-maps
- Simpler timestamp str format
=> Simpler NV uploads

neuroscout/resources/predictor.py
- Minor fix which makes it easier for pyNS to get collection status
=> Fix get predictors collection id name

neuroscout/populate/ingest.py
Reverts neuroscout/neuroscout#635
=> Revert "Use derivatives = false to exclude preprocessed files"

neuroscout/config/datasets/ds001145.json, neuroscout/config/datasets/ds001510.json, neuroscout/config/feature_schema.json
Ingest `StructuredNarrative` / ds001510 dataset.
Also sets up `TwilightZone` for ingestion, but stimulus questions are holding that up.
=> Add new datasets, and update feature schema for RMS

neuroscout/config/bibliography.json, neuroscout/frontend/src/analysis_builder/Builder.tsx, neuroscout/resources/analysis/endpoints.py
- Fixes #586 
- Add "Sherlock" and "StructuredNarrative" to bibliography
- Fixes bug in bib.py where error will occur if there is no dataset entry
=> Fix navbuttons and update bibliography

neuroscout/frontend/src/analysis_builder/Status.tsx, neuroscout/frontend/src/api.ts, neuroscout/frontend/src/coretypes.ts
=> update neurovault upload status component/api calls

neuroscout/frontend/src/analysis_builder/Predictors.tsx, neuroscout/frontend/yarn.lock
=> predictor table header width fix

neuroscout/frontend/src/analysis_builder/Builder.tsx, neuroscout/frontend/src/analysis_builder/Transformations.tsx, neuroscout/frontend/src/analysis_builder/transforms.ts, neuroscout/frontend/src/api.ts, neuroscout/frontend/src/coretypes.ts
=> Add  ReplaceNA to scale xform, fix unselect all predictors error.

neuroscout/tasks/upload.py
Fixes the type sent to Neurovault API
=> Fix variance API type

neuroscout/models/analysis.py, neuroscout/resources/analysis/reports.py, neuroscout/schemas/analysis.py
=> Show NV collections in full analysis route

neuroscout/config/predictor_schema.json
=> MNT: Add motion outlier (fmriprep) to predictor schema

.travis.yml
https://launchpad.net/~jonathonf
=> Fix travis ffmpeg PPA

.travis.yml, neuroscout/populate/extract.py, neuroscout/populate/transform.py
- Add Task as filter to `create_predictors`
- Only apply transformation if there are matching Predictors
=> Fix ingestion issues with multiple tasks

neuroscout/config/datasets/ds001132.json, neuroscout/config/datasets/ds001545.json, neuroscout/config/datasets/forrest.json, neuroscout/config/datasets/hbn.json, neuroscout/config/datasets/raiders.json, neuroscout/config/datasets/sherlockmerlin.json, neuroscout/config/transformers.json, neuroscout/populate/extract.py, postgres/Dockerfile, postgres/pg_dump-to-s3/pg_dump-to-s3.sh
- FIX: Filter Task using dataset_id in `create_predictors`
- MNT: Upgrade postgres to 12
=> FIX: Filter Task using dataset_id, MNT: Upgrade postgres to 12

neuroscout/frontend/src/analysis_builder/transforms.ts
=> Add missing binarize option. 

neuroscout/config/feature_schema.json
- `num_faces` should not be disabled.
=> FeatureSchema: num_faces is not categorical

neuroscout/tasks/upload.py
Ensures contrast name regex is correct
=> Truncate contrast name in NV upload

.travis.yml, neuroscout/Dockerfile, neuroscout/config/bibliography.json, neuroscout/config/datasets/ds001131.json, neuroscout/config/datasets/ds001132.json, neuroscout/config/datasets/ds001338.json, neuroscout/config/datasets/ds001510.json, neuroscout/config/datasets/ds001545.json, neuroscout/config/datasets/forrest.json, neuroscout/config/datasets/hbn.json, neuroscout/config/datasets/life.json, neuroscout/config/datasets/raiders.json, neuroscout/config/datasets/sherlockmerlin.json, neuroscout/config/feature_schema.json, neuroscout/config/transformers.json, neuroscout/models/task.py, neuroscout/optional_requirements.txt, neuroscout/populate/annotate.py, neuroscout/requirements.txt
- Extracts Audioset Labels
- Fixes bug in `avg_run_duration` computation
- Updates bibliography for Audioset and BERT extractors
=> Extract Audioset Labels

neuroscout/Dockerfile, neuroscout/requirements.txt
=> Fix docker image tensorflow requirement

neuroscout/frontend/src/analysis_builder/ContrastEditor.tsx, neuroscout/frontend/src/analysis_builder/Contrasts.tsx, neuroscout/frontend/src/coretypes.ts
Should be just `Type` not `ContrastType` in BIDS StatsModel.
Fixes #751
=> FIX: Contrast: Type not ContrastType

neuroscout/frontend/src/analysis_builder/Builder.tsx, neuroscout/frontend/src/analysis_builder/Report.tsx
=> Fix logic when regenerating available runs from existing model.

neuroscout/resources/analysis/reports.py
=> Truncate NV Collection names to 200 chars

neuroscout/tasks/utils/build.py
This speeds up reports by about another 2 seconds per.
If we ever need to reset the saved layouts, the files can just be deleted and they will be automatically recreated
=> Save partial layout

celery_worker/tasks.py
- Remove defunct arguments to generate_report
=> Remove defunct report args

neuroscout/frontend/src/Routes.tsx
=> If user is loading new empty analysis lets assume they own it.

docs/builder/transformations.md, neuroscout/frontend/src/analysis_builder/transforms.ts, neuroscout/frontend/src/coretypes.ts
=> Remove logical operations

neuroscout/frontend/src/predictor_collection/AddPredictorsForm.tsx, neuroscout/frontend/src/predictor_collection/FilesAndRunsForm.tsx, neuroscout/schemas/predictor.py
=> Require Predictor Collection name

neuroscout/models/analysis.py, neuroscout/resources/analysis/reports.py, neuroscout/schemas/analysis.py, neuroscout/schemas/user.py
Closes #832 
- Need to add upload to neuroscout-cli package, test, and release
=> Log neuroscout-cli and fmriprep versions when uploading results

neuroscout/config/datasets/ds002837.json
At 1hz, to keep things the same for now (until we switch to offline models).
=> Video to Frame conversion for NND

neuroscout/populate/convert.py, neuroscout/populate/extract.py, neuroscout/populate/ingest.py, neuroscout/populate/utils.py, neuroscout/requirements.txt
- Direct inserts instead of `bulk_insert_model` which is much faster and skips ORM alltogethr
- Check `mimetype` before loading models, prevents unnecessary loading
=> Improve extraction speed

.github/workflows/publish-docs.yml, docs/index.md
This should build and publish docs to gh-pages using mkdocs automatically w/ GH Actions.
=> GH Action to build and publish mkdocks

neuroscout/core.py, neuroscout/resources/__init__.py, neuroscout/resources/run.py
=> Add stimulus timing route

README.md, docs/cli/index.md, docs/cli/usage.md, neuroscout/frontend/src/analysis_builder/Status.tsx, site/builder/index.html, site/cli/index.html
Related `neuroscout-cli` PR: https://github.com/neuroscout/neuroscout-cli/pull/127
=> Update docs to reflect new CLI directory structure

neuroscout/tasks/utils/build.py
Fixes issue where HRF convolve variable had incorrect length. Introduced in #821
=> Fix HRF duration

nginx/nginx.conf
I had to add a couple exception to the routing to enable `react-router` to work properly
=> FIX: Nginx routing for gzip enable

neuroscout/Dockerfile, neuroscout/frontend/src/analysis_builder/Report.tsx
=> Fix Correlation plot, and upgrade node to 12

docker-compose.yml
=> Add log file in central location

neuroscout/frontend/src/analysis_builder/Builder.tsx, neuroscout/frontend/src/analysis_builder/Overview.tsx, neuroscout/frontend/src/analysis_builder/Predictors.tsx, neuroscout/frontend/src/analysis_builder/Report.tsx
Closes #865  and adds a tooltip explaining modality (closes #880 as its not  longer necessary)
=> Make tooltips more obvious, add modality tooltip, and fix modality numbers

neuroscout/tasks/upload.py
=> unlink file after sucessfull upload

neuroscout/requirements.txt
Reverts neuroscout/neuroscout#1017
=> Revert "Bump pillow from 8.2.0 to 9.0.0 in /neuroscout"

neuroscout/frontend/src/analysis_builder/Builder.tsx, neuroscout/frontend/src/analysis_builder/Review.tsx
Would occur on analyses with descriptions, removed curly brackets wrapping analysis Description in review tab. 
Closes #1038
=> Fix crash in review tab for some analyses.

docs/browse/index.md, docs/builder/index.md, docs/builder/predictors.md, docs/builder/review.md, docs/builder/run.md, docs/builder/transformations.md, docs/cli/colab.md, docs/cli/index.md, docs/faq.md, docs/index.md, mkdocs.yml
read through the docs. added a google colab section to the docs. minor renaming sections and headings. fixed typos
=> update docs, add google colab

neuroscout/frontend/cypress.config.ts.tests, neuroscout/populate/setup.py, setup_frontend_tests.sh
- Also fix frontend test config
=> FIX: Datalad installation path
