web/models/analysis.py, web/resources/analysis.py, web/tests/api/test_analyses.py
To close #83 and #84 
#84 was straightforward, I added an unstructured JSON field for "config"
For #83, "transformations" field now takes an array of structure JSON  that conforms to the Transformation schema. I've also added a schema for "parameters". This might be overkill but should ensure appropriate inputs. 
My only question is if we should be referring to predictor names in inputs or predictor ids. The latter seems less error prone but is less human readable.
=> Added config field, and nested transformation field

README.md, neuroscout/auth.py, neuroscout/config/config.py, neuroscout/core.py, neuroscout/database.py, neuroscout/db_utils.py, neuroscout/mail.py, neuroscout/manage.py, neuroscout/models/auth.py, neuroscout/populate.py, neuroscout/resources/__init__.py, neuroscout/resources/user.py, neuroscout/resources/utils.py, neuroscout/templates/confirm.html, neuroscout/templates/password_reset.html, neuroscout/templates/welcome_email.html, neuroscout/tests/api/test_analyses.py, neuroscout/tests/api/test_user.py, neuroscout/tests/conftest.py, neuroscout/utils.py
WIP. Resolves:
- #79 - Sends emails to users 
To-do
=> Send email confirmation/verification/reset links to users

celery_worker/tasks.py, neuroscout/tests/conftest.py
Minor PR fixes:
- A bug where entities where not passed to `load_event_variables`, in case not all runs were select for a task
- Old reference to predictor names in test model
=> Filter runs in compile

neuroscout/config/transformers.json, neuroscout/populate/convert.py, neuroscout/tests/data/fake_transcript.csv, neuroscout/tests/test_models.py
To ingest `Despicable Me` transcript, it was necessary to resample, or rather adjust the onsets by a ratio. It seems the stimulus used in the study was played 4-5% slower than the DVD version, and thus the script was off by a small amount. 
This also adds the ability to use a single transcript for several subclips (e.g. a single movie aligned transcript for 6 sub clips, each with their respective on/offsets).
=> Transcript cutoffs and resample_ratio

docker-compose.yml, nginx/sites-enabled/flask_project
Fixes #239 by increasing timeout to 300s. Now most compile requests should pass, but it's still annoying to  have to wait that long, so in the future, it would be best to do long running SQL queries in celery itself (see other PR #242)
=> FIX compile timeout

celery_worker/tasks.py
Write out a sidecar with the TR, so that the full dataset is not needed to find the the TR of the tasks' runs
=> Writeout preproc sidecar

neuroscout/models/analysis.py, neuroscout/models/predictor.py, neuroscout/resources/analysis/endpoints.py, neuroscout/resources/predictor.py, neuroscout/resources/utils.py, neuroscout/tests/api/test_predictor.py
This PR attempts to work around #239, and the generally slowness of submitting an analysis for compilation.
The issue is that the query is slow to get the PredictorEvents required for writing out bundle / compiling. We could run this query in Celery, but setting up Celery to be aware of SQLAlchemy, Flask + models is a pain, and requires a lot of restructuring.
An easy solution, is to simply have a status "Submitting" which is true after a user has clicked compile, but before the query has finished and the task has been submitted to Celery.
This way, the frontend can just stop caring about the response to `/compile` and instead just poll `/status` to see how the analysis is getting on. This may cause problems with scalability, but we can deal with that problem later, if we are that …
=> Add "submitting" status, to workaround slow compile queries

neuroscout/requirements.txt, neuroscout/resources/analysis/endpoints.py
Despite efforts to speed up the `/compile` route, it was still taking too long and potentially timing out.
The two bottlenecks where: SQLAlchemy ORM and Marshmallow on up to millions of rows.
Thus, I moved to using core SQLAlchemy,  and manually serializing the results using a custom function. 
This leads to a speed up of almost an order of magnitude (probably ~5-7x) faster on average.
Downsides is we are relying on the order of columns, but this seems to be guaranteed by SQLAlchemy.
=> Speed up /compile route

neuroscout/config/feature_schema.json, neuroscout/models/features.py, neuroscout/populate/modify.py, neuroscout/populate/transform.py
This PR:
1. Fixes a bug in `update_annotations` that prevent matching to `extractor_name`
2. Updated extractor feature schema descriptions.
Left to do:
=> Updated extractor descriptions

neuroscout/models/predictor.py, neuroscout/resources/predictor.py, neuroscout/scripts/build_static.sh, neuroscout/scripts/init_reset.sh, neuroscout/scripts/nuke_docker_db.sh, neuroscout/tests/api/test_predictor.py
Closes #232 
Instead of caching a stored values for PredictorRun values. For now, instead, will add dynamic properties to Predictors which use SQLAlchemy to compute these values. A bit costly, but caching should for the most part solve this issue.
=> Add statistics at the Predictor level

docker-compose.dev.yml, neuroscout/resources/analysis/schemas.py, neuroscout/resources/dataset.py, neuroscout/resources/predictor.py, neuroscout/resources/user.py, neuroscout/tests/api/test_analyses.py, neuroscout/tests/api/test_predictor.py
This PR implements a backwards changing API change. Runs and predictors now dump and load with flat lists of ids, rather than lists of objects with "id" as an item. This was original this way due to a marshmallow issue (asymetrical dumping/loading). Looks like this is getting fixed in 3.0, but it's still in beta, and upgrading seems to cause other problems that I rather not deal with now.
Also, I fixed some small schema errors, and the Swagger UI URL for Development mode.
=> API Change: Dump/load flat lists for predictors and runs

README.md, docker-compose.dev.yml, neuroscout/frontend/src/App.tsx, neuroscout/frontend/src/Builder.tsx, neuroscout/frontend/src/ContrastEditor.tsx, neuroscout/frontend/src/Overview.tsx, neuroscout/frontend/src/coretypes.ts, neuroscout/frontend/src/transforms.ts, neuroscout/frontend/src/utils.ts, neuroscout/frontend/tsconfig.prod.json, neuroscout/frontend/yarn.lock, nginx/nginx.dev.conf
This is forked from bug-fixesv.2 branch so that should be merged first.
This allows filtering runs by run number, subject, and session simultaneously. 
When you test it pay attention to how select all works, if you change your filters it will reselect everything that matches your filter. I wasn't readily able to find out how to stop that from happening. If it seems like something that should behave differently than it does let me know.
=> Run filtering

neuroscout/frontend/src/Builder.tsx, neuroscout/frontend/src/Overview.tsx
fixes #359
The code added that automatically selects runIds when a dataset is selected happens is a promise and was getting executed after the code that checked to see if new predictors should be loaded. Went ahead and set the flags to load predictors and allow access to the predictors tab.
=> Fix bug with auto selected run IDs.

celery_worker/tasks.py, neuroscout/manage.py, neuroscout/populate/ingest.py, neuroscout/populate/json.py, neuroscout/requirements.txt, neuroscout/tests/test_models.py
Closes #367 
TODO:
- Since `exclude` is being deprecated we need a way to specific which event files to look for in `fitlins` (see: https://github.com/neuroscout/neuroscout-cli/issues/52). This may require changing the file names for bundle files.
=> Update pybids to 0.7

neuroscout/frontend/src/App.tsx, neuroscout/frontend/src/Browse.tsx, neuroscout/frontend/src/Builder.tsx, neuroscout/frontend/src/ContrastEditor.tsx, neuroscout/frontend/src/Home.tsx, neuroscout/frontend/src/Overview.tsx, neuroscout/frontend/src/Status.tsx, neuroscout/frontend/src/auth.actions.ts, neuroscout/frontend/src/auth.store.ts
This PR is a relatively big aesthetic change to the UI.
The main change is the use of a Menu bar at the top, and flipping the Builder tabs to be vertical.
The main things left to do for now:
Later on we can fill the "My Profile" and "Help" tabs with content.
@rwblair can you take care of those things, and take a good look and give me some feedback? I'm not 100% sure the routing is correctly implemented
=> Menu/tab UI overhaul

celery_worker/tasks.py, neuroscout/frontend/src/Builder.tsx, neuroscout/frontend/src/Status.tsx, neuroscout/resources/analysis/reports.py
This PR allows users to skip building the analysis object (aka validating through pybids) when compiling the bundle.
@rwblair can you add an option to skip building in the analysis builder?
I'm imagining it would either be a checkbox (that when you uncheck it it warns you with a modal to confirm), or a setting under a hidden 'advanced' settings toggle.
=> Allow skipping Analysis build

neuroscout/resources/analysis/reports.py
The build parameter was being passed to the `get` route, even though it didn't need it (and would cause it to crash)
=> HOTFIX: Only need build argument on post not get

neuroscout/resources/analysis/reports.py
This was messing with the swagger docs, and not recognizing the correct arguments.
=> HOTFIX: Move kwargs to above doc

neuroscout/frontend/src/Builder.tsx, neuroscout/frontend/src/Report.tsx
always set 'postReports' true when analysis is updated and saved. Always save analysis when going to report tab.
fixes #426
=> Allow reports to be generated multiple times per session if analysis is updated.

neuroscout/core.py, neuroscout/resources/__init__.py, neuroscout/resources/analysis/__init__.py, neuroscout/resources/analysis/endpoints.py, neuroscout/resources/analysis/schemas.py, neuroscout/resources/predictor.py, neuroscout/tests/api/test_analyses.py
WIP.
Adds a route at `/api/analyses/{ID}/fill`.
This is a `POST` route. It will try to fill sensible defaults for the following fields:
- `runs`: Defaults to all runs
- `predictors`: Will look in model and try to find names from `X`. Then will query for all the latest predictors for the specified runs matching those names.
Note that this is not a `PUT` route, so changes to the model (e.g. blanking `predictors`) will have to be done using the appropriate route.
Closes #462
=> Add auto-fill functionality

celery_worker/tasks.py, neuroscout/frontend/src/App.css, neuroscout/frontend/src/App.tsx, neuroscout/frontend/src/Builder.tsx, neuroscout/frontend/src/Contrasts.tsx, neuroscout/frontend/src/Report.tsx, neuroscout/frontend/src/Status.tsx, neuroscout/frontend/src/auth.actions.ts, neuroscout/resources/analysis/reports.py, neuroscout/tests/api/test_dataset.py
Closes #453 
I pushed a change to allow non-logged in users to request a report.
However, I think the issue is actually in the frontend code, because when I tried it without being logged in, only a `GET` was ever seen in the server logs, and never a `POST`. This is probably the original source of the bug.
Also, two more minor issue to fix in this PR:
@rwblair can you finish this PR off, plesae?
=> Fix report generation issues

neuroscout/models/analysis.py, neuroscout/models/auth.py, neuroscout/models/dataset.py, neuroscout/models/features.py, neuroscout/models/group.py, neuroscout/models/predictor.py, neuroscout/models/run.py, neuroscout/models/stimulus.py, neuroscout/populate/ingest.py, neuroscout/populate/utils.py, neuroscout/resources/analysis/endpoints.py, neuroscout/resources/analysis/reports.py, neuroscout/resources/analysis/schemas.py, neuroscout/resources/dataset.py, neuroscout/resources/predictor.py, neuroscout/resources/run.py, neuroscout/tests/api/test_analyses.py, neuroscout/tests/api/test_predictor.py, neuroscout/tests/conftest.py, neuroscout/tests/test_models.py
WIP. Closes #475 
Removing dynamic non-lazy joins and on the fly stats on Predictors took the response of `/api/predictors` from 38s to 3s.
=> Speed up API

neuroscout/resources/dataset.py, neuroscout/resources/predictor.py, neuroscout/resources/utils.py
Closes #473 
I'm removing our custom cache key function, and replacing it with the build in query string support. This will ignore the order of the arguments. 
Actually ignoring invalid arguments is not as easy, because the libraries that parse the query string, and cache don't talk. We could add this functionality but I honestly think its not necessary because its rare we'll get so many invalid requests (especially if using Swagger or `pyns`) as to cause a problem. In addition, flask-caching handles the disk size of the cache, so unless that becomes a problem, I think we are OK.
=> Ignore query string order. Closes # 473

neuroscout/frontend/src/Builder.tsx, neuroscout/frontend/src/ContrastEditor.tsx, neuroscout/frontend/src/Contrasts.tsx, neuroscout/frontend/src/HelperComponents.tsx, neuroscout/frontend/src/Transformations.tsx, neuroscout/frontend/src/coretypes.ts
fixes #443, set another flag in the main store for the initial load of predictors. We want predictors to be loaded the first time we see runIDs populated, which is several re-renders deep from the constructor since we wait on the api.
fixes #389 consolidated the code that displays form validation error messages to be consistent across tabs that display them, just transforms and contrasts right now.
=> 443 389 preload predictors consistent form err

neuroscout/frontend/src/Predictors.tsx
First commit enables pagination and sets the page size to 200.
=> Fix slow predictor table rendering.

neuroscout/config/transformers.json, neuroscout/populate/extract.py
Closes #541 
I decided on a 90% default
That code in general is not the most efficient and a bit hard to debug, but I can't think of a much better way to do it for now.
At least this will speed things up by only processing useful Features (i.e. those in most runs).
=> Only create Predictors for EFs present in 90% of runs

neuroscout/populate/convert.py
- Minor changes to successfully import files from Rev API. 
- Extract more text related features.
=> Ingest Rev API Text

neuroscout/frontend/src/AnalysisList.tsx, neuroscout/frontend/src/App.css, neuroscout/frontend/src/Builder.tsx, neuroscout/frontend/src/coretypes.ts, neuroscout/frontend/src/utils.ts
datasets were moved to props of builder out of state, updated update analysis
function accordingly. Fixes #555 
Disable next button on contrast tab if no contrasts present. Never set
flag to generate reports if no contrasts exist. Fixes #537
Have analyses names line break if too long. Fixes #562
Non existent analysis IDs will now redirect to /builder/. Fixes #484
on error codes 400 and above do not attempt to parse response as json, just
return status code so component can figure out what it wants to do.
Fixes #527
=> Fixes for frontend regressions.

celery_worker/tasks.py, neuroscout/resources/analysis/reports.py
Often, uploads were failing because of compressed file corruption error.
This might be because due to incorrect read mode, and context headers.
=> Fix tarball upload

neuroscout/frontend/src/Contrasts.tsx
=> filter out contrasts whose source is 'fmriprep' in autocontrast creation

neuroscout/frontend/src/Status.tsx, neuroscout/frontend/src/api.ts
Currently will only display latest failed attempt with traceback, and will only show latest pending attempt with traceback if there are no successes. All success shown if available. Not sure how to word the failed and pending titles.
API endpoint currently only hit on initial analysis load and when the analysisId changes.
=> [WIP] Link to neurovault uploads.

neuroscout/frontend/src/Builder.tsx
Also when loading an existing analysis enable all tabs if any contrasts have been made.
=> Add button to convolve all non fmriprep predictors. 

celery_worker/viz.py, neuroscout/frontend/src/Transformations.tsx, neuroscout/frontend/src/coretypes.ts, neuroscout/frontend/src/transforms.ts
=> Fix normalize dm, and remove some transforms

neuroscout/resources/analysis/endpoints.py
Fixes #585 
What was actually happening is that I changed the name of the analyses post-compilation. 
The easy fix here is to not change the `modified_at` timestamp for trivial changes post-compilation, such as `name` `description` or `private` status.
=> Avoid re-doing report for minor post-DRAFT changes

.travis.yml, celery_worker/app.py, celery_worker/requirements.txt, celery_worker/tasks.py, neuroscout/core.py, neuroscout/resources/analysis/reports.py, neuroscout/tasks/upload.py
Predictors were not being generated correctly (looping was done wrong, and nans were not skipped) This should fix that.
=> Fix create predictor collection

celery_worker/tasks.py, neuroscout/frontend/src/analysis_builder/Status.tsx, neuroscout/resources/predictor.py, neuroscout/tasks/upload.py, neuroscout/tasks/viz.py, neuroscout/tests/api/test_predictor.py
You can now pass an object/dictionary as `descriptions` when you `POST` to /api/predictors/collection`.
This lets you set the description for each of the columns in your events. In the future, we can expand this to add more meta-data but for now I think it's all we need.
=> Add optional description to predictor upload

neuroscout/resources/predictor.py, neuroscout/tests/api/test_predictor.py
Merged #632 too soon. requests can pass dictionary, so i'm going to try dumping as string, and reading that in on the server side.
=> Use json string for collection description

neuroscout/populate/ingest.py
This is a better approach than using `desc=None`, which will fail if no derivatives have been linked yet.
=> Use derivatives = false to exclude preprocessed files

neuroscout/models/predictor.py
There is an issue where the DB on disk is taking up 50GB. 49 of these are in the `predictor_event` tale. 
This is largely due to lack of compression / indexes, as the PG_DUMP is only ~600MB.
Well, this is also largely due to the poor decision to write the value for every predictor/onset in that table, even when the same is shown across subjects.
Here's what I get from running some stats on both `extracted_event` and `predictor_event`;
Extracted Event
Predictor Event
This shows that from the core relation (core data stored), `predictor_event` is only about 13x larger, which makes sense given the data duplication that sometimes occurs. 
The issue seems to be indexes. I got a little index happy when we had some performance issues. 
So I ran some stats on the indexes in the db:
It looks like …
=> Index / db maintenance

neuroscout/resources/analysis/reports.py
NV only displays the full_dataset_url. We were using that to link back to the raw data, but until NeuroVault/NeuroVault#723 is implemented, we can use the full_dataset_url.
=> Link directly to NeuroScout in NeuroVault

neuroscout/core.py, neuroscout/populate/extract.py, neuroscout/populate/modify.py, neuroscout/resources/__init__.py, neuroscout/resources/predictor.py, neuroscout/schemas/predictor.py, neuroscout/tasks/utils.py, neuroscout/tests/api/test_predictor.py, neuroscout/tests/conftest.py, neuroscout/tests/test_models.py
Fixes #642 
It's easy enough (if a bit redundant) to dynamically generate `PredictorEvents` for `Predictors` from extractors. It remains to be seem how slow this is (especially for Reports).
However, we still need the `PredictorEvent` table for `Predictors` that come from event files (and could differ between subjects), and uploaded PredictorCollection (as they don't link to stimuli). We could potentially add another table here to reduce redundancy but it doesn't seem worth it.
=> Remove PredictorEvents from Predictors derived from ExtractedFeatures

docker-compose.yml, neuroscout/frontend/package.json, neuroscout/frontend/src/config.ts.example, nginx/sites-enabled/flask_project, nginx/sites-enabled/ssl_config
Adds redirect from `alpha.neuroscout.org` to `neuroscout.org` and changes the official domain to the latter.
@tyarkoni can you check that the DNS for `www.neuroscout.org` is set up correctly? I was able to extend the cert to include the bare domain and alpha, but www. does not work. (Now I'm timed out from trying again for a while)
=> Migrate domain to bare neuroscout.org and add redirect

neuroscout/tasks/compile.py
Fixes #664 
This allows pybids to ingest predictors that are missing in a specific run. 
Workaround.
=> Write out empty dfs for missing predictors

neuroscout/frontend/src/App.tsx, neuroscout/frontend/src/auth.store.ts
Also clears analyses on logout. Also fixes a problem with checking the truthiness of isGAuth in the authstore.
=> Fix analyses not showing on logout -> login

neuroscout/tasks/report.py
Closes #663 
Adds required neuroscout-cli to compiled bundles
=> Adds version to bundles

neuroscout/frontend/src/analysis_builder/Status.tsx
fixes #673. I haven't tested this yet.
=> forgot to format variable in string properly

neuroscout/config/datasets/sherlockmerlin.json, neuroscout/populate/ingest.py
Re-enable and update the Sherlock Merlin dataset.
- Fixes bug related to pybids > 0.8. `layout.get_collections` would return incorrect result because preproc and raw file interfered in variable loading.
- Ensure re ingesting does not cause conflict with old `RunStimulus`
=> Update Sherlock Merlin

docs/builder/index.md
edited "getting started" in documentation with warning on Google accounts not being supported when accessing API via pyNS.
=> added warning on google accounts and pyNS

neuroscout/resources/analysis/reports.py
Uploads were failing because the user supplied name can be the same.
=> Add hash_id to collection_name NV upload

neuroscout/frontend/src/analysis_builder/Builder.tsx, neuroscout/frontend/src/analysis_builder/Report.tsx
This is inefficient, every time the review tab is navigated to it hits the api to redownload results.
Before I had the conditional around the reports tab in builder the report state would properly update with the new reports as necessary but the default active plot in the plots tabs would not rerender with the new results.
=> force reconstruct of review tab for fresh results on model change

neuroscout/frontend/src/analysis_builder/Builder.tsx, neuroscout/frontend/src/analysis_builder/Overview.tsx, neuroscout/frontend/src/analysis_builder/Report.tsx, neuroscout/frontend/src/css/App.css, neuroscout/frontend/src/utils/index.ts
Fixes #533 #686 
Currently no warning on number of runs selected. @adelavega any idea at what number we might want to warn at?
This also assumes that the api returns run plots in the same order that front end asks for them.
=> Add ability to generate and view reports for any run.

neuroscout/core.py, neuroscout/resources/__init__.py, neuroscout/resources/predictor.py, neuroscout/schemas/predictor.py, neuroscout/tasks/utils/io.py, neuroscout/tests/api/test_predictor.py, neuroscout/utils/db.py
Closes #706
This generalized the logic used in `tasks.io` to dump `PredictorEvents` even for `ExtractedEvents`. It creates `PredictorEvents` on the fly when necessary. Otherwise, it uses fast dumping for regular `PredictorEvents`.
Same function is used for dumping events in celery/tasks.
=> Restore predictor-events route, dumps extracted events

neuroscout/frontend/src/analysis_builder/Builder.tsx, neuroscout/frontend/src/analysis_builder/Contrasts.tsx
Fixes #678
Also when a predictor is removed from the predictors tab any contrast that includes it is also removed.
=> Dedupe auto contrasts

neuroscout/config/feature_schema.json, neuroscout/resources/predictor.py
Closes  #728
- Deactivates categorical variables by default
- Adds `active` as kwargs to `PredictorList` resource/API route
This should not change how pyNS or the frontend client interactive with the API.
=> Deactivate categorical variables

neuroscout/resources/predictor.py
Previously, setting active to False for `/api/predictors/` resulted in only inactive `Predictors` being shown. `active_only` shows both when `False`
=> Active_only in predictor route, not just active

neuroscout/tasks/upload.py
In worker, accept F test stat images as valid upload types to NeuroVault
=> Add f test to upload types

neuroscout/Dockerfile, neuroscout/requirements.txt, postgres/Dockerfile
The cron package is missing from the postgres image, preventing build.
(this branch includes the fix for missing tensorflow https://github.com/neuroscout/neuroscout/issues/745 https://github.com/neuroscout/neuroscout/pull/746)
=> missing cron package

docker-compose.yml, neuroscout/config/datasets/ds001132.json, neuroscout/config/datasets/ds001338.json, neuroscout/config/datasets/ds001510.json, neuroscout/config/datasets/ds001545.json, neuroscout/config/datasets/forrest.json, neuroscout/config/datasets/god.json, neuroscout/config/datasets/hbn.json, neuroscout/config/datasets/life.json, neuroscout/config/datasets/raiders.json, neuroscout/config/datasets/sherlockmerlin.json, neuroscout/config/feature_schema.json, neuroscout/config/transformers.json, neuroscout/populate/annotate.py, neuroscout/populate/extract.py
=> Add graphs to windowed extraction

neuroscout/tasks/utils/build.py
Fixing upstream pybids issue with handling single event predictors (or those with all `n/a`s) by adding a duration of 1 to the empty events.
Fixes #773
=> Fix division by zero error when empty predictor

neuroscout/resources/predictor.py, neuroscout/schemas/predictor.py, neuroscout/utils/db.py
This PR allow users to say `predictor_timing=True` in the `/predictor-events` route and get back information about the stimulus associated with the event, including the timing information (for that run) and path (truncated) of the stimulus used.
For now, I'm not serving the stimuli to the world, so this is only useful internally.
=> Add stimulus timing to /predictor-events route

neuroscout/frontend/src/Routes.tsx, neuroscout/frontend/src/analysis_builder/Builder.tsx
Fixes #759.
Redirects back to main page and displays a warning if user attempts to browse non public dataset that they don't own.
This would prevent private analyses from being viewed by non owners who have the id, is that something we want?
=> check if analysis is public or owned before rendering analysis builder in routes

neuroscout/frontend/src/AnalysisList.tsx, neuroscout/frontend/src/App.tsx, neuroscout/frontend/src/Routes.tsx, neuroscout/frontend/src/coretypes.ts
Allow analyses and public analyses to be null by default. If null we show loading symbol on analyses list. If there are no analyses or and error occurs the analyses variable recieves an empty list so the loading symbol will go away.
fixes #776
=> Adds loading spinner for public/private analyses list.

neuroscout/frontend/src/App.tsx, neuroscout/resources/analysis/endpoints.py, neuroscout/resources/user.py
/myanalyses is quite slow right now.
One improvement is to only return the fields that matter for the listing, for both private and public analyses.
This seems to reduce the data transfered by 5x and speed up the query by up to 10x. 
However, I'm still getting a situation where the query hangs on the frontend, and I only see a spinning icon. 
I tested this with an account with only a few analyses, so I don't think having too many analyses is the issue.
Instead, I think there's scenarios where the logic goes awry and it just hangs.
=> Speed up and fix My Analyses

neuroscout/Dockerfile, neuroscout/api_spec.py, neuroscout/models/dataset.py, neuroscout/requirements.txt, neuroscout/resources/analysis/endpoints.py, neuroscout/resources/analysis/reports.py, neuroscout/resources/dataset.py, neuroscout/resources/predictor.py, neuroscout/resources/run.py, neuroscout/resources/task.py, neuroscout/resources/user.py, neuroscout/schemas/analysis.py, neuroscout/schemas/dataset.py, neuroscout/schemas/predictor.py, neuroscout/schemas/run.py, neuroscout/schemas/user.py, neuroscout/tasks/utils/io.py, neuroscout/tests/api/test_analyses.py, neuroscout/tests/api/test_predictor.py, neuroscout/tests/api/test_run_task.py
We're using a fairly old version of Marshmallow, so I'm upgrading to v3, and upgrading `webargs` `flask_apispec` as well.
In the process, I also updated the Dockerfile to buster from stretch.
=> Update to Marshamallow 3, also upgrade webargs flask_apispec

celery_worker/requirements.txt, docker-compose.yml, neuroscout/Dockerfile, neuroscout/core.py, neuroscout/frontend/src/AnalysisList.tsx, neuroscout/frontend/src/Home.tsx, neuroscout/frontend/src/Routes.tsx, neuroscout/frontend/src/analysis_builder/Builder.tsx, neuroscout/frontend/src/analysis_builder/Overview.tsx, neuroscout/frontend/src/analysis_builder/Review.tsx, neuroscout/frontend/src/analysis_builder/Status.tsx, neuroscout/frontend/src/analysis_builder/transforms.ts, neuroscout/frontend/src/api.ts, neuroscout/frontend/src/css/App.css, neuroscout/models/analysis.py, neuroscout/requirements.txt, neuroscout/resources/__init__.py, neuroscout/resources/analysis/__init__.py, neuroscout/resources/analysis/endpoints.py, neuroscout/resources/analysis/reports.py, neuroscout/resources/dataset.py, neuroscout/resources/predictor.py, neuroscout/schemas/analysis.py, neuroscout/tasks/report.py, neuroscout/tasks/utils/build.py, neuroscout/tasks/utils/warnings.py, neuroscout/tests/api/test_analyses.py, neuroscout/tests/api/test_predictor.py, neuroscout/utils/db.py
- Closes #823 
- Allow united analyses until compilation (then backend rejects compilation until you provide a name).
-  Closes #833 and #838 
- Switch to 5 char UUID, checking for clashes upon generation
- Closes #770 by throwing warning if any n/as are found in variables. It suggesting using the Scale transformation to remove n/as.
- Default option for scale is to replace n/a with 0 after scaling.  
- Closes #795. Minor API improvements.
=> Various UI improvements + Pybids 0.12.3

neuroscout/config/feature_schema.json, neuroscout/core.py, neuroscout/resources/__init__.py, neuroscout/resources/extractor.py, neuroscout/schemas/extractor.py, neuroscout/tests/api/test_extractor.py
For #820 #870 need API route with descriptions for extractors.
Instead of adding to the db and over-complicating, I decided to just scrape the doc strings from Pliers and return via API. We can cache this route to ensure adequate performance.
=> Add Extractor description API route

neuroscout/populate/extract.py
To address memory problems with Clarifai Extractor, serializing objects early should save memory
=> Serialize objects early to save memory

neuroscout/frontend/src/analysis_builder/Report.tsx, neuroscout/frontend/src/analysis_builder/Status.tsx
After merging master locally and then making this branch with a commit only touching Reports.tsx,  `yarn start` is failing at Status.tsx error for some reason.
=> set scale to default to false on report plots if we get a report without scaling informaiton

neuroscout/core.py, nginx/nginx.conf
Addresses #908 by adding gzip to Nginx. 
The problem was the wrong mimetype was issued for json files, and flask served the main index.html file, not nginx.
=> Gzip files, by serving w/ nginx not flask

neuroscout/core.py, neuroscout/resources/__init__.py, neuroscout/resources/extractor.py, neuroscout/utils/misc.py
Closes #923 + adds a route for it. This would help in documentation as well
=> add distinct extractor route

neuroscout/frontend/src/analysis_builder/Builder.tsx
=> Dont add runs to bids model if all runids selected.

neuroscout/models/dataset.py
Fix #986 
Bug in computing mean age caused all ages to be displayed as `n/a`
=> Fix demographics

.github/workflows/tests.yml, neuroscout/frontend/src/AnalysisList.tsx
=> Filters for analysis table

neuroscout/Dockerfile
looks like the existing key-server is deprecated: https://sks-keyservers.net/
This changes the keyserver to the one suggested by neurodebian: https://neuro.debian.net/
=> [FIX] change keyserver to ubuntu

.env.example, nginx/nginx.conf
If the swagger containers hostname wouldn't resolve nginx would fail to start. I put in the set directive by its proxypass to get around nginx trying to do the hostname lookup on startup. Nginx was complaining about not having a resolver when you visited /api/swagger. Made change according to this:
https://sandro-keil.de/blog/let-nginx-start-if-upstream-host-is-unavailable-or-down/
=> set resolver to dockers internal dns for first 30 seconds

docs/cli/docker.md, docs/cli/index.md, docs/cli/singularity.md, docs/cli/usage.md, mkdocs.yml, neuroscout/frontend/src/analysis_builder/Status.tsx
For Neuroscout-CLI v0.6 release
=> Update CLI docs

.github/workflows/deploy.yml, docker-compose.dev.yml, docker-compose.prod.yml, docker-compose.yml, neuroscout/Dockerfile, neuroscout/frontend/src/config.ts.prod
Picks up where #1083 left off:
In all cases, must specify two files, such as :
`docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d`
In the following, the local directory is mapped to `/neuroscout` where `gunicorn` runs
- `docker-compose.dev.yml`: Builds image locally, and also maps port `4000` to allow `yarn start`
- `docker-compose.build.yml`: Builds image locally
- `docker-compose.image.yml`: Pulls image from GHCR, with environment variable `${IMAGE_TAG}` setting the TAG (i.e. `master`, a version, or a pull request).
In `docker-compose.dev.yml`: we run off `/usr/src/app` which is pre-built including the frontend. The image is also fixed to `master`.
=> Add production mode and trigger deployment to staging

docker-compose.dev.yml, docker-compose.prod.yml, neuroscout/Dockerfile
Must nest `neuroscout` folder one layer deep to be able to use it as a WSGI app
=> FIX: Dockerfile environment for production
